<?php
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\user\Entity\User;
use Drupal\Core\Form\FormStateInterface;



/**
 * Implements hook_theme() to add the template definition.
 **/
function clearview_infotech_theme($existing, $type, $theme, $path)
{
      return [
            'clearview_template' => [
              'variables' => ['clearview_var' => []],
            ],
            'site_create_form' => [
              'render element' => 'form',
            ],

          ];
        }

/**
 * Implements hook_theme_suggestions_page() to set 40x template suggestions
 */
function clearview_infotech_theme_suggestions_page(array $variables)
{
    $path_args = explode('/', trim(\Drupal::service('path.current')->getPath(), '/'));
    $suggestions = theme_get_suggestions($path_args, 'page');
    $http_error_suggestions = [
        'system.401' => 'page__401',
        'system.403' => 'page__403',
        'system.404' => 'page__404',
    ];
    $route_name = \Drupal::routeMatch()->getRouteName();
    if (isset($http_error_suggestions[$route_name])) {
        $suggestions[] = $http_error_suggestions[$route_name];
    }

    return $suggestions;
}

function clearview_infotech_user_login(User $user) {
  $email = $user->getEmail();
  $nids = \Drupal::entityQuery('node')
      ->condition('type','workspace')
      ->condition('status', 1)
      ->condition('field_users.entity.field_email', $email)
      ->sort('nid', 'DESC')
      ->range(0, 1)
      ->execute();
      //dump($nids);exit;
  // if(!empty($nids) ){
    // $response = new RedirectResponse('/admin/content');
    // $response->send();
    // $nid = array_values($nids)[0];
    // dump($nid);exit;
    $url = Url::fromRoute('entity.node.canonical', ['node' => 1]);
    $response =  new RedirectResponse($url->toString());
    $response->send();
  // }   
  // We want to redirect user on login.
  // $response = new RedirectResponse("admin/content");
  // $response->send();
  // return;
}
